name: check
on:
  push:
    branches: [main]
    tags:
      - "*"
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: docker
    container:
      image: node:23.9.0-alpine
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install PNPM
        run: |
          npm install -g pnpm
      - name: Install dependencies
        run: |
          pnpm install
      - name: Run checks
        run: |
          pnpm check
      - name: Run tests
        run: |
          pnpm test
      - name: Run sample vite build
        run: |
          pnpm build
      - name: Run sample package
        run: |
          pnpm prepare
